### ISSUE TITLE
articles show layout

### ISSUE THREAD

**Issue by gwalda19** [gwalda19/webFinalProject#14]
articles show page needs to be updated.

**Comment by Boolander** [comment]
I centered the title image in the center of the article, and formatted everything else.  Take a look and see what you think.

**Comment by Boolander** [comment]
Oh, if you have any suggestions color/formatting/etc let me know. I'm sure I can do whatever you want.

**Comment by Boolander** [comment]
I'm thinking about getting rid of the home button, and making the trending icon and maybe the title text go to the same page.  Any thoughts?

**Comment by Boolander** [comment]
Oh yea, I removed the code from models/user.rb that was fucking up the rake db:seed.  You'll probably have to tweak it to put it back.
