### ISSUE TITLE
remove formatting needs from article creation

### ISSUE THREAD

**Issue by gwalda19** [gwalda19/webFinalProject#18]
don't make the user add formatting tags.

**Comment by Boolander** [comment]
I don't know how to get around adding double break tags to separate paragraphs in the body, but all of the other formatting taken care of by the index.html.erb files.

**Comment by Boolander** [comment]
Oh, if you have any suggestions color/formatting/etc  let me know.  I'm sure I can do whatever you want.

**Comment by Boolander** [comment]
Users are going to have to add <br><br> where they want paragraph breaks.
